[workspace]
members = [
  "crates/apps/app_auth",
  "crates/apps/cross_publisher",
  "crates/apps/janitor",
  "crates/apps/url_shortener",

  "crates/libraries/commons",
  "crates/libraries/mastodon",
  "crates/libraries/stubs",
  "crates/libraries/twitter",
]
