[package]
name = "iwt_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_derive = "1.0"
oauth2 = "4.2.3" #TODO: maybe we should re-export the models we need
toml = "0.5"