[package]
name = "iwt_commons_stubs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oauth2 = "4.2.3"
iwt_commons = { path = "../commons"}