name: Flake Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flake-check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v17
    - name: Install Cachix
      uses: cachix/cachix-action@v10
      with:
        name: indieweb-tools
        authToken: ${{ secrets.CACHIX_TOKEN }}
    - name: Use cache
      run: cachix use indieweb-tools
    - name: Flake Check
      run: nix flake check
    - name: Push deps
      run: nix path-info .#indieweb-tools-deps | cachix push indieweb-toolsx
